FROM dockerjenhar/daviz:v1

EXPOSE 8888
ADD requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt
RUN apt update
COPY ./app /app
COPY ./app/data /tmp/data
COPY ./app/run-notebook.sh /usr/local/bin/run-notebook.sh
RUN chmod +x run-notebook.sh
CMD [ "run-notebook.sh" ]


