version: "3"
services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ~/data/:/app/data
      - ~/poi_icon/:/app/assets/poi_icon

  notebook:
    image: rendyaswin/notebook:latest
    build:
      context: .
      dockerfile: Dockerfile.notebook
    ports:
      - "10000:8888"
    volumes:
      - ~/data/:/app/data
      - ~/poi_icon/:/app/assets/poi_icon
